####################################################################################
#                                                                                  #
#                           study APP YML PROPERTIES                               #
#                                                                                  #
####################################################################################


####################################################################################
#                                  Server                                          #
####################################################################################
server:
  port: 5656
  servlet:
    context-path: /aims
  error:
    path: /error
    include-stacktrace: never # always | never
    whitelabel.enabled: true
  logging:
    level:
      org:
        hibernate: info

jwt:
  token:
    header: X-Auth-Token
    secret: manager?dev?aims
    expiration: 604800
    origin: aims

sys:
  msg:
    error: \uC694\uCCAD\uC744 \uCC98\uB9AC\uD558\uB358 \uC911 \uC54C\uC218 \uC5C6\uB294 \uC624\uB958\uAC00 \uBC1C\uC0DD\uD588\uC2B5\uB2C8\uB2E4.<br>\uC2DC\uC2A4\uD15C\uAD00\uB9AC\uC790\uC5D0\uAC8C \uBB38\uC758 \uD558\uC2ED\uC2DC\uC624.

####################################################################################
#                                DEFAULT                                       #
####################################################################################
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: true # JPA를 통해 실행된 쿼리 표시
    properties:
      hibernate:
        format_sql: true # 콘솔에 표시되는 쿼리를 가독성 있게 표시
        enable_lazy_load_no_trans: true
    logging:
      level:
        org:
          hibernate: info

---
####################################################################################
#                                DEV                                           #
####################################################################################
spring:
  profiles: dev
  datasource:
    tomcat:
      initial-size: 15
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 8
      default-auto-commit: true
    type: org.apache.tomcat.jdbc.pool.DataSource
#    hikari:
#      pool-name: hikari-cp
#      maximum-pool-size: 30
#      minimum-idle: 2
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true
    url: jdbc:mysql://localhost:3306/test?useSSL=false

    username: tester
    password: qwert12345


  jpa:
    hibernate:
      ddl-auto: validate # create | create-drop | none \ update | validate
  jackson:
    default-property-inclusion=non_null:

  logging:
    level:
      org:
        hibernate: info

---
####################################################################################
#                                TST                                           #
####################################################################################
spring:
  profiles: tst
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: tester
    password: qwert12345

  jpa:
    hibernate:
      ddl-auto: validate # create | create-drop | none \ update | validate
  jackson:
    default-property-inclusion=non_null:

  logging:
    level:
      org:
        hibernate: info

---
####################################################################################
#                                prod                                          #
####################################################################################
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
    username: tester
    password: qwert12345

  jpa:
    hibernate:
      ddl-auto: create # create | create-drop | none \ update | validate
  logging:
    level:
      org:
        hibernate: info